Repository VerifiedInc/Kredita-Demo-Web, pull requests merged in 2023-12, with the labels that each got.

#37 feat: 1 Click
  .circleci/config.yml
  .env.example
  .gitignore
  app/Layout.tsx
  app/config.client.ts
  app/config.ts
  app/context/AppContext.tsx
  app/features/register/components/OneClickForm.tsx
  app/features/register/components/RegularForm.tsx
  app/features/register/types.ts
  app/hooks/useIsOneClick.ts
  app/images/kredita-logo.png
  app/root.tsx
  app/routes/register.tsx
  package-lock.json
  package.json
  remix.config.js
Labels: 10 min review

#39 1 click
  app/components/InputMask.tsx
  app/components/PhoneInput.tsx
  app/coreAPI.server.ts
  app/features/register/components/OneClickForm.tsx
  app/routes/register.tsx
  app/styles/theme.ts
  app/validations/phone.schema.ts
  package-lock.json
  package.json
Labels: hotfix, 5 min review

#38 [CI] updated to push the release image to production
  .circleci/config.yml
Labels: hotfix, 1 min review, single-line

#40 refactor: remove credential requests from one click endpoint
  app/coreAPI.server.ts
Labels: 1 min review, single-line

#41 feat: set fullname credential as session identifier
  app/routes/index.tsx
  app/routes/register.tsx
  app/routes/verified.tsx
  app/session.server.ts
Labels: 1 min review

#42 refactor: add first name only to session
  app/routes/register.tsx
Labels: hotfix, single-line
