Repository VerifiedInc/Kredita-Demo-Web, pull requests merged in 2024-01, with the labels that each got.

#43 fix: typo.
  app/features/register/components/OneClickForm.tsx
Labels: hotfix, 1 min review, single-line

#44 [CSP] docs url added to frame-ancestors
  server.js
Labels: 1 min review

#45 chore: upgrade node version to 20.10.0-alpine
  Dockerfile
  package.json
Labels: 1 min review

#46 fix: submit form on phone input change and valid
  app/features/register/components/OneClickForm.tsx
  app/routes/register.tsx
Labels: hotfix, 1 min review

#48 chore: change to signup
  app/coreAPI.server.ts
Labels: hotfix, 1 min review, single-line

#49 add reenter signout
  app/features/register/components/OneClickForm.tsx
  app/routes/index.tsx
  app/routes/register.tsx
  app/routes/verified.tsx
  app/styles/theme.ts
Labels: 5 min review

#50 feat: add redirect to url and request 1-click with code only
  app/coreAPI.server.ts
  app/features/register/components/OneClickForm.tsx
  app/routes/register.tsx
Labels: 1 min review

#51 fix: keep session of redirect param
  app/features/register/components/OneClickForm.tsx
  app/routes/index.tsx
  app/routes/verified.tsx
  app/session.server.ts
Labels: hotfix, 5 min review

#52 chore: add search params to verified page
  app/routes/register.tsx
Labels: 1 min review

#54 chore: update legal text
  app/features/register/components/OneClickForm.tsx
Labels: 1 min review, single-line

#56 chore: get brand api key
  .env.example
  README.md
  app/config.ts
  app/coreAPI.server.ts
  app/root.tsx
  app/routes/register.tsx
  app/session.server.ts
Labels: 5 min review

#58 fix: add input mode numeric in inputProps
  app/components/PhoneInput.tsx
Labels: 1 min review, single-line

#57 small fixes
  app/Layout.tsx
  app/features/register/components/OneClickForm.tsx
Labels: 1 min review

#59 [CI] updated to deploy the white labelled version.
  .circleci/config.yml
Labels: hotfix, 5 min review

#60 brand session
  app/root.tsx
  app/routes/favicon.tsx
  package-lock.json
  package.json
  public/manifest.json
  public/verifiedinc.webp
Labels: hotfix, 10 min review

#61 chore: add more observability
  app/coreAPI.server.ts
  app/routes/register.tsx
Labels: hotfix, 1 min review

#62 brand session
  app/session.server.ts
Labels: hotfix, 1 min review

#63 chore: remove cookie usage
  app/features/register/components/OneClickForm.tsx
  app/hooks/useBrand.ts
  app/root.tsx
  app/routes/register.tsx
Labels: hotfix, 1 min review

#64 1 click credentials
  app/coreAPI.server.ts
  app/routes/register.tsx
  package-lock.json
  package.json
Labels: 5 min review

#65 refactor: remove default options
  app/coreAPI.server.ts
Labels: 1 min review, single-line
