Repository VerifiedInc/Kredita-Demo-Web, pull requests merged in 2024-02, with the labels that each got.

#66 chore: persist brand uuid with redirect url
  app/coreAPI.server.ts
  app/features/logout/usecases/logoutUseCase.ts
  app/features/register/components/OneClickForm.tsx
  app/root.tsx
  app/routes/index.tsx
  app/routes/register.tsx
  app/routes/verified.tsx
  app/utils/getBrandSet.ts
Labels: 5 min review

#67 fix: clone request
  app/routes/verified.tsx
Labels: hotfix, 1 min review, single-line

#68 fix: add brand name and space fix
  app/routes/verified.tsx
Labels: 1 min review, single-line

#69 chore: handle cancel use case
  app/features/logout/usecases/logoutUseCase.ts
  app/routes/register.tsx
  app/utils/getFormDataOrEmpty.server.ts
Labels: 1 min review

#70 chore: add logs
  app/coreAPI.server.ts
  app/utils/getBrandSet.ts
Labels: hotfix, 1 min review

#71 fix: access full name conditionally
  app/routes/register.tsx
Labels: hotfix, 1 min review

#73 feat: add notice alert
  .env.example
  .prettierignore
  app/Layout.tsx
  app/config.client.ts
  app/config.ts
  app/root.tsx
Labels: 5 min review

#72 feat: 1 click non hosted
  .env.example
  app/components/OTPInput.tsx
  app/components/PhoneInput.tsx
  app/config.client.ts
  app/config.ts
  app/coreAPI.server.ts
  app/features/personalInformation/hooks/usePersonalInformationFields.ts
  app/features/personalInformation/types.ts
  app/features/register/components/OneClickForm.tsx
  app/features/register/components/OneClickFormNonHosted.tsx
  app/features/register/components/OneClickHeader.tsx
  app/features/register/components/OneClickLegalText.tsx
  app/hooks/useField.ts
  app/hooks/useIsOneClickNonHosted.ts
  app/root.tsx
  app/routes/personal-information.tsx
  app/routes/register.tsx
  app/utils/getBrand.ts
  app/validations/birthDate.schema.ts
  app/validations/country.schema.ts
  app/validations/email.schema.ts
  app/validations/field.schema.ts
  app/validations/oneClickNonHosted.schema.ts
  app/validations/ssn.schema.ts
  app/validations/state.schema.ts
Labels: 10 min review

#74 1 click non hosted
  app/Layout.tsx
  app/coreAPI.server.ts
  app/features/logout/usecases/logoutUseCase.ts
  app/features/register/components/OneClickForm.tsx
  app/features/register/components/OneClickFormNonHosted.tsx
  app/features/register/components/OneClickPromptDialogContent.tsx
  app/features/register/components/OneClickSMSDialogContent.tsx
  app/routes/index.tsx
  app/routes/personal-information.tsx
  app/routes/register.tsx
  app/routes/verified.tsx
  app/utils/getBrand.ts
Labels: hotfix, 10 min review

#75 chore: control hosted/non-hosted by query param
  .env.example
  app/config.client.ts
  app/config.ts
  app/features/logout/usecases/logoutUseCase.ts
  app/hooks/useIsOneClickNonHosted.ts
  app/root.tsx
  app/routes/personal-information.tsx
  app/routes/register.tsx
Labels: 1 min review

#76 fix: typo
  app/features/register/components/OneClickLegalText.tsx
Labels: 1 min review, single-line
